/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: aadityaadexter (https://sketchfab.com/aadityaadexter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pepsi-tin-with-texture-c45ce808e47e4658960c35febef0d47e
Title: Pepsi Tin with Texture
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Pepsi = (props) => {
  const { nodes, materials } = useGLTF('/assets/models/pepsi.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -2.71]} scale={1.256}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 1.43, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials['Material.001']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials['Material.002']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_7.geometry}
              material={materials['Material.001']}
              position={[0.005, 0.191, -0.037]}
              rotation={[0.016, -0.135, 0.002]}
              scale={[1, 0.389, 1]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/pepsi.glb')

export default Pepsi
